apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-1
spec:
  steps:
    - name: step-1
      image: registry.access.redhat.com/ubi8/ubi:8.3-297      
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi   
      script: >
        #!/usr/bin/env sh

        ls -al /
    - name: step-2
      image: registry.access.redhat.com/ubi8/ubi:8.3-297      
      resources:
        limits:
          cpu: 200m
          memory: 1000Mi
        requests:
          cpu: 200m
          memory: 512Mi   
      script: >
        #!/usr/bin/env sh

        uname -a
    - name: step-3
      image: registry.access.redhat.com/ubi8/ubi:8.3-297      
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi   
      script: >
        #!/usr/bin/env sh

        ls -al /        